/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0507f6f3d852fcc7fa307d3712550f44)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface PreviewEnv {
		CACHE: KVNamespace;
		BUCKET: R2Bucket;
		DB: D1Database;
		ANALYTICS: AnalyticsEngineDataset;
		ASSETS: Fetcher;
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_URL: string;
		RESEND_API_KEY: string;
		RESEND_FROM: string;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		GITHUB_CLIENT_ID: string;
		GITHUB_CLIENT_SECRET: string;
		SENTRY_DSN_SERVER: string;
		CRON_SECRET: string;
	}
	interface Env {
		CACHE: KVNamespace;
		BUCKET: R2Bucket;
		DB: D1Database;
		ANALYTICS: AnalyticsEngineDataset;
		ASSETS: Fetcher;
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_URL: string;
		RESEND_API_KEY: string;
		RESEND_FROM: string;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		GITHUB_CLIENT_ID: string;
		GITHUB_CLIENT_SECRET: string;
		SENTRY_DSN_SERVER: string;
		CRON_SECRET: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "RESEND_API_KEY" | "RESEND_FROM" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "SENTRY_DSN_SERVER" | "CRON_SECRET">> {}
}
