/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env preview --include-runtime=false` (hash: d75832e895eaf4e7ca4df88af9aa5bcb)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env {
		DB: D1Database;
		SHEET_ID: string;
		SHEET_GID: string;
		SHEET_REVALIDATE_SECONDS: string;
		DATE_COLUMN: string;
		NEXT_PUBLIC_METERED_API_URL: string;
		NEXT_PUBLIC_METERED_API_KEY: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SHEET_ID" | "SHEET_GID" | "SHEET_REVALIDATE_SECONDS" | "DATE_COLUMN" | "NEXT_PUBLIC_METERED_API_URL" | "NEXT_PUBLIC_METERED_API_KEY">> {}
}
